### ISSUE TITLE
Mortal Kombat: Mythologies Sub-Zero (USA) - Game ID does not work.

### ISSUE THREAD

**Issue by atds55** [MrPalloncini/PicoMemcard#6]
In the game Mortal Kombat: Mythologies Sub-Zero - Game ID is not working. In sd2psx it works, so the game should send the ID, but for some reason the picomemcard is not recognizing it.

Edit:In PSIO the game ID of this game works, but in XStation it does not work. On sd2psx the game ID of this game works on PSIO and XStation.

**Comment by MrPalloncini** [comment]
There was an issue while getting a game id that didn't end with ';' it should be fixed in the next release
