### ISSUE TITLE
Mortal Kombat: Mythologies Sub-Zero (USA) - problem with save.

### ISSUE THREAD

**Issue by atds55** [MrPalloncini/PicoMemcard#7]
With the new FW, every time I load Mortal Kombat Mythologies Sub-Zero or use the mem cards option in XStation, the picomemcard creates a new memory card and, without using the memory card already created.

![image](https://github.com/MrPalloncini/PicoMemcard/assets/72902338/b2691881-794b-4af2-81a2-ae74ed58e6a3)

**Comment by MrPalloncini** [comment]
Does this happen with other games as well?
EDIT: i think i've fixed the issue, there was a small mistake, nice catch!

**Comment by atds55** [comment]
> Does this happen with other games as well? EDIT: i think i've fixed the issue, there was a small mistake, nice catch!

I only observed this behavior with this game.
