### ISSUE TITLE
Castlevania SOTN saving freeze

### ISSUE THREAD

**Issue by whitezombie2000** [MrPalloncini/PicoMemcard#9]
Someone first reported this issue in the PSIO Discord with the PSxMemCard. We thought it was an issue with the individual's PSIO set up but we were incorrect. In my previous testing I didn't really test write operations with Castlevania SOTN after the person reported it. This is an issue with the Pico PSxMemCard and not the PSIO. I went to the first save point in the game and reproduced the issue on the second save attempt.  Reset, tried again, and it took 15 save attempts. I also reproduced the issue on the X-Station after about 15 save attempts. I did about 50 save operations with the MemCard PRO and could not get the game to lock up. Also, I re-flashed realJoshByrnes's v1.0.22 fork and did about 50 save attempts. I could not re-produce the issue with his fork.

Here's a video of the issue. After the write operation it can randomly freeze.

https://youtu.be/e6lnqw3ig6I

**Comment by Jad3d87** [comment]
I've had this happen a few times. If you wait around 2 minutes you can reset the console and a usable save will be there. Not sure why this might happen. Maybe the game is trying to move ahead before the card is ready?

**Comment by whitezombie2000** [comment]
That same person reported a freezing issue too with the PSxMemCard and this game. It happened to them after loading a game 35+ times reported. It seems rare, but it did freeze for me once too. I had this happen when loading a save. I had loaded around 30-40 times when doing some write tests. I have no idea if this occurred on the other fork, with the X-Station, or from a CD. Quite honestly I'm a little burned out on testing, lol. 

https://youtu.be/8ZGDQebKEK0

I can tell you some behavior I noticed though. After getting the game to freeze when trying to save, if you restart the console, load the game (or any game), the card doesn't blink blue, as it just stays green. Usually when you start a game it will blink blue and switch back to green. If you reset after a freeze, load CSOTN in this state, try to save the game, it will freeze every time unless you pull out the card, or power cycle the console. But it will eventually freeze again anyway.

**Comment by whitezombie2000** [comment]
I can tell you some behavior I noticed though. After getting the game to freeze when trying to save, if you restart the console, load the game (or any game), the card doesn't blink blue, as it just stays green. Usually when you start a game it will blink blue and switch back to green. If you reset after a freeze, load CSOTN in this state, try to save the game, it will freeze every time unless you pull out the card, or power cycle the console. But it will eventually freeze again anyway.

**Comment by atds55** [comment]
> Alguém relatou esse problema pela primeira vez no PSIO Discord com o PSxMemCard. Achamos que era um problema com a configuração PSIO do indivíduo, mas estávamos errados. Em meus testes anteriores, eu realmente não testei as operações de gravação com Castlevania SOTN depois que a pessoa relatou isso. Este é um problema do Pico PSxMemCard e não do PSIO. Fui ao primeiro ponto de salvamento do jogo e reproduzi o problema na segunda tentativa de salvamento. Reinicie, tentei novamente e foram necessárias 15 tentativas de salvamento. Também reproduzi o problema no X-Station após cerca de 15 tentativas de salvar. Fiz cerca de 50 operações de salvamento com o MemCard PRO e não consegui travar o jogo. Além disso, atualizei novamente o fork v1.0.22 do realJoshByrnes e fiz cerca de 50 tentativas de salvar. Não consegui reproduzir o problema com o garfo dele.
> 
> Aqui está um vídeo do problema. Após a operação de gravação, ele pode congelar aleatoriamente.
> 
> [https://youtu.be/TGdaC1neYfM ](https://youtu.be/TGdaC1neYfM)

I couldn't replicate the problem. I saved 50 times and the game didn't crash, it saved normally. Could it be related to the SD card or console model? I tested it on a SCPH-1000, with PSIO in midboot k1v4. My 512MB SD is formatted with cluster 512 bytes. This is the SD that came with the PsxMemCard from bitfunx.

**Comment by whitezombie2000** [comment]
I have a NTSC SCPH-5501 for the PSIO and the X-Station. I did test 2 PSxMemCards and used the 512MB card that came with it. I also tried a couple other 32GB SD cards and had the same issue. I have a NTSC SCPH-1001 that can barley read discs, several PSone models,  PM-41, and PM-41 (2) I could probably test when I have time. The PSxMemCards I have were purchased around March 2023. I also wonder if something could have changed with the manufacturing of the cards. The back of mine say v1.2 20220920.

Edit: My NTSC SCPH-1001 and NTSC SCPH-101 PSone had the same issue from a disc.

![PSxMemCard_1](https://github.com/user-attachments/assets/1aa0b584-14f3-4d5f-9854-17b5aea7de42)

![PSxMemCard_2](https://github.com/user-attachments/assets/34693788-0dcc-4448-b5fb-91b8c0c0573c)

**Comment by atds55** [comment]
> I have a NTSC SCPH-5501 for the PSIO and the X-Station. I did test 2 PSxMemCards and used the 512MB card that came with it. I also tried a couple other 32GB SD cards and had the same issue. I have a NTSC SCPH-1001 that can barley read discs, several PSone models, PM-41, and PM-41 (2) I could probably test when I have time. The PSxMemCards I have were purchased around March 2023. I also wonder if something could have changed with the manufacturing of the cards. The back of mine say v1.2 20220920.
> 
> Edit: My NTSC SCPH-1001 and NTSC SCPH-101 PSone had the same issue from a disc.
> 
> ![PSxMemCard_1](https://private-user-images.githubusercontent.com/23583562/356235831-1aa0b584-14f3-4d5f-9854-17b5aea7de42.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMjc5MzIsIm5iZiI6MTcyMzEyNzYzMiwicGF0aCI6Ii8yMzU4MzU2Mi8zNTYyMzU4MzEtMWFhMGI1ODQtMTRmMy00ZDVmLTk4NTQtMTdiNWFlYTdkZTQyLkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDE0MzM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlZGIwM2EyMjE2YTc4ZGE0N2JhNTMwNTgwNTk0YTU0OTFjOTZlMDYwODg1NDkzYWFlYWViZTA3MThmNDg1YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yFanWCeEwYMx05c0U-5XyMhNmqpozRHIBmLBDLqQerQ)
> 
> ![PSxMemCard_2](https://private-user-images.githubusercontent.com/23583562/356235879-34693788-0dcc-4448-b5fb-91b8c0c0573c.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMjc5MzIsIm5iZiI6MTcyMzEyNzYzMiwicGF0aCI6Ii8yMzU4MzU2Mi8zNTYyMzU4NzktMzQ2OTM3ODgtMGRjYy00NDQ4LWI1ZmItOTFiOGMwYzA1NzNjLkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDE0MzM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiMTMzZTVhZDNlZjc1MWY0M2M3OGUyMTNhY2UyYTQ5NDA5MTQ5MzQ1OTY3OTMzYTIyN2NhZGZkZWM1Zjg2MTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uhJ_xjFDfFMLtJ_uXkcD1wfX1vyMwiyZymFgU-uXwQk)

My picomemcard is the same as yours.
So it must be a random problem, in my test the problem did not occur.

**Comment by MrPalloncini** [comment]
This might be a problem regarding the pio timing between the read/write operation, similiar to issue #5 however, i dom't have a LA nor a way to check how the game itself expects the data.

**Comment by nullpointer-br** [comment]
> Here's a video of the issue. After the write operation it can randomly freeze.
> 
> https://youtu.be/TGdaC1neYfM

Try change configuration to LE_K1V2 mode...

**Comment by atds55** [comment]
> > Here's a video of the issue. After the write operation it can randomly freeze.
> > https://youtu.be/TGdaC1neYfM
> 
> Try change configuration to LE_K1V2 mode...

Castlevania Symphony of the Night doesn't work well in loadexec, so using the game in loadexec k1v2 will cause game problems at some point. This game only works well from start to finish in midboot. So loadexec may have solved the problem with picomemcard, but it will cause problems during game play.

**Comment by whitezombie2000** [comment]
> > Here's a video of the issue. After the write operation it can randomly freeze.
> > https://youtu.be/TGdaC1neYfM
> 
> Try change configuration to LE_K1V2 mode...

This issue is not related to the PSIO operation. It can happen from an X-Station, or a CD too, as I wrote above, it's an issue with this PSxMemCard's firmware fork, and doesn't seem to occur on the original release by dangiu, or realJoshByrnes's v1.0.22 fork. It could possibly affect other games but I have not tested many games.

**Comment by nullpointer-br** [comment]
> This issue is not related to the PSIO operation. It can happen from an X-Station, or a CD too, as I wrote above, it's an issue with this PSxMemCard's firmware fork, and doesn't seem to occur on the original release by dangiu, or realJoshByrnes's v1.0.22 fork. It could possibly affect other games but I have not tested many games.

Maybe it's not related to PSIO but change operation mode indeed make a difference in my tests.
Every time I run Castlevania using MB_K1V4 mode this "coffin spinning" glitch occurs.
If I change to MB_K1V5_SPUH or LE_K1V2 save works every time.
Hope these observations help developer of this fork to solve this bug.

**Comment by whitezombie2000** [comment]
I tested those modes on PSIO and they all froze for me when saving. Also, at this time MrPalloncini doesn't own a PSIO.

**Comment by atds55** [comment]
What does this have to do with the Symphony of the night problem and picomencard (psxmencard)?

**Comment by whitezombie2000** [comment]
Closing as the issue won't likely be fixed. If MrPalloncini feels the need to re-open the issue or if someone can trouble shoot the issue, then we can re-open it.
